# This file may be used to create an environment using:
# $ conda create --name gprMax --file <this file>

name: gprMax
dependencies:
- python>=3.4
- colorama
- cython
- h5py
- jupyter
- matplotlib
- mpi4py
- numpy
- psutil
- pyqt=4.11.4
- scipy

- pip:
  - terminaltables
  - tqdm
  - python-slugify
